config/routes.rb
Light::Application.routes.draw do
  get "display/index"
  resources :movies

  root :to => 'display#index', :as => 'display'

  get :controller=>"movies", :action=>"search" 

  post :controller=>"display", :title=>"*", :action=>"show"
  post :controller=>"display", :title=>"Nothing in Common", :action=>"show"
  post :controller=>"display", :title=>"Ferris Bueller's Day Off", :action=>"show"
  post :controller=>"display", :description=>"Tom Hanks and Jackie Gleeson are estranged father and son who come together.", :action=>"show"
  post :controller=>"display", :trivia=>"Jackie Gleason's last movie maybe?", :action=>"show"

  post 'layouts/_search_results', :controller =>"layouts", :action => 'show'   

end

app/models/movie.rb
class Movie < ActiveRecord::Base

def self.search(search)
  search_condition = "%" + search + "%"
  find(:all, :conditions => ['title LIKE ? OR description LIKE ?', search_condition, search_condition])
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 def search
  @movies = Movie.search params[:search]
  end

end

app/controllers/display_controller.rb
class DisplayController < ApplicationController
  def index
    @movies = Movie.limit(1).order("RANDOM()")
  end

  def search
    @movies = Movie.search params[:search]
  end



end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

def search
  @movies = Movie.search params[:search]
  end

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render action: 'show', status: :created, location: @movie }
      else
        format.html { render action: 'new' }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:image_url, :title, :year, :director, :description, :trivia, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/display_helper.rb
module DisplayHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/display/index.html.erb
<header>

<div id="logo">


    <h1> lights, <br />  camera,  <br />
     <strong><em>Chicago!</em></strong><br /> <img src="/assets/newstar.png" height="30" width="27" />
    <img src="/assets/newstar.png" height="30" width="27" /> <img src="assets/newstar.png" height="30" width="27" /> <img src="assets/newstar.png" height="30" width="27" /></h1>

</div>
</header>

<h1>Display#index</h1>

<div id="main">

<% @movies.each do |movie| %>
  <div class="entry">


  <ul>
 <li><strong>title</strong>: <%= movie.title %></li>
 <li><strong>description</strong>:   <%= sanitize(movie.description) %></li>
 <li><strong>trvia</strong>:   <%= sanitize(movie.trivia) %></li>
 <li><strong>location</strong>:   <%= sanitize(movie.location) %></li>
  </ul>
  </div>

<% end %>
</div>

<div id="blurb">
<p class="blurb">Find locations where Chicago movies were filmed!</p>

  <!-- this find button is just a placeholder for now -->
   <section id="find">
      <input type="text" placeholder="enter keyword" id="term" />
      <button id="search">Find movie </button>
   </section>
</div>

  <footer>
	<ul>
	<li>About</li> <li>Contact</li> <li>Showtimes</li>  <li>News</li>
   </footer>









<p>Find me in app/views/display/index.html.erb</p>

app/views/display/search_results.html.erb
 <ul>
    <% @grants.each do |grant| %>
  <li><%= link_to grant.title, 
    :action => 'show', :id => grant.id  %></li>
  <% end %>
  </ul>

app/views/layouts/_search_results.html.erb
CTYPE html>
<html>
<head>
</head>

 <ul>
    <% @movies.each do |movie| %>

  <li><%= link_to @movies ,

    :action => 'show', :title => movie.title   %></li>

    :action => 'show', :description  => movie.description   %></li>
    :action => 'show', :trivia  => movie.trivia   %></li>


  <% end %>
  </ul>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Light</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>





<%= yield %>




</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :trivia %><br>
    <%= f.text_field :trivia %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <thead>
    <tr>
      <th>Image url</th>
      <th>Title</th>
      <th>Year</th>
      <th>Director</th>
      <th>Description</th>
      <th>Trivia</th>
      <th>Location</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.image_url %></td>
        <td><%= movie.title %></td>
        <td><%= movie.year %></td>
        <td><%= movie.director %></td>
        <td><%= movie.description %></td>
        <td><%= movie.trivia %></td>
        <td><%= movie.location %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image url:</strong>
  <%= @movie.image_url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Trivia:</strong>
  <%= @movie.trivia %>
</p>

<p>
  <strong>Location:</strong>
  <%= @movie.location %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>